name = ""
code = ""
connector_id = "aws.glue"
enabled = true

connection {
  aws {
    #url = "http://localhost:8080"
    access_key_id=""
    secret_access_key=""
    session_token=""
    region = ""
  }

  # (Advanced) define the size of batch of items loaded by each request in inventory.
  #fetch_page_size =
}