name = ""
code = ""
connector_id = "aws.glue"
enabled = true

connection {
  aws {
    #url = "http://localhost:8080"
    access_key_id=""
    secret_access_key=""
    session_token=""
    region = ""
  }

  # (Advanced) define the size of batch of items loaded by each request in inventory.
  #fetch_page_size =
}

# Filter
#
# Filter the items that should be keep in the inventory.
# Use the rich filter language described in documentation.
# https://docs.actian.com/zeenea/#page/Technical%20Documentation/zeenea-filters.html
#
# filter keys are:
#   database : the database name.
#   table  : the table name.
#
# Example:
#   filter = """
#              database starts with 'CUSTOM_' and not table ends with '_BAK'
#           or database ~ 'INTERN_*' and table ~ /(?:HR|IT|MARKET)_FIGURES/
#   """
#
# Note: Filter can contain either the raw value or a file URL to the content.
# Example:
#   filter = "file:///path/to/zeenea/connections/glue-filter.json"
#
# When using an side-file, filter changes are taken into account without restarting the scanner.
#
# filter = ""