name = ""
code = ""
connector_id = "databricks-v2"
enabled = true

# Define the catalog code associated with the connection ("default" when empty).
# catalog_code = ""

# Defines the list of aliases used by other connectors to generate lineage link.
# alias = ["localhost:1234/db","https://some-url.org"]

# Define secret manager for this connection. 
# This configuration only works with Scanner 73+ and needs a functional secret manager configured in the scanner configuration file.
#secret_manager {
#    enabled = true
#    key = "<secret_name>"
#}

connection {
  url = ""
  # The HTTP path part of the JDBC connection to retrieve User defined tags
  # jdbc:databricks://<hostname>:<port>/default;transportMode=http;ssl=1;AuthMech=11;Auth_Flow=1;httpPath=<httpPath>;
  # ex: http_path = "/sql/1.0/warehouses/<id>"
  http_path = ""

  oauth {
    client_id = ""
    client_secret = ""

    # Optional - OAuth2 endpoint (example: "https://<tenant>.cloud.databricks.com/oidc/v1/token")
    endpoint = 
    # Optional - OAuth2 scope (example: "all-apis")
    scope = 
  }
}

# Table-level lineage is always fetched via REST unconditionally
# Column-level lineage (field_to_field) is disabled by default
#
# fetching the column lineage can be done (enabled = true)
#  * using the REST API for free (strategy = "rest_api") but it's known to be slow
#  * using sql (strategy = "jdbc_compute") but it involves compute cost from the provider
#
# Prerequisites when enabling jdbc_compute:
#   1. Set connection.http_path above.
#   2. Grant the service principal "Can use" or "Can run" on the SQL warehouse.
#   3. Give the service principal read access like so
#      GRANT USE CATALOG ON CATALOG system TO `<service_principal>`;
#      GRANT USE SCHEMA ON SCHEMA system.access TO `<service_principal>`;
#      GRANT SELECT ON TABLE system.access.column_lineage TO `<service_principal>`;
lineage {
  field_to_field {
    enabled = false
    strategy = "rest_api"
  }
}


# Activate Tags (true/false)
# Both system and governed tags are retrieved, but we can't distinguish them
#
# Prerequisites when enabling:
#   1. Set connection.http_path above.
#   2. Grant the service principal "Can use" or "Can run" on the SQL warehouse.
#   3. For each catalog, grant SELECT on the tag views:
#        GRANT SELECT ON `<catalog>`.information_schema.table_tags  TO `<service_principal>`;
#        GRANT SELECT ON `<catalog>`.information_schema.column_tags TO `<service_principal>`;
#
# If tags are enabled and any of the above is not set properly, the import will fail shortly
tags {
  enabled = false
}



# Filter used to keep only items that match this filter.
#
# Use universal filter language described in documentation.
# https://docs.actian.com/data-intelligence-platform/technical-documentation/scanners/zeenea-universal-filters.html
#
# Rules filter keys are :
# - catalog       : Databricks catalog / database
# - schema        : Databricks schema
# - table         : Databricks table
#
# Example:
#filters = [
#  {
#    id="accept_zeenea_dataset"
#    action = ACCEPT
#    rules {
#      dataset = "ZEENEA*"
#    }
#  },
#  {
#    id = "default_reject"
#    action = REJECT
#  }
#]
#
# filters = []

# proxy {
#     #  proxy scheme (choose https or http)
#     scheme =
#     hostname =
#     port =
#     username =
#     password =
# }

#tls {
#  truststore {
#    # Path to the trust store file
#    path = 
#    # Password of the trust store file.
#    password = 
#    # Type of the trust store file. (PKCS12 ou JKS), default value is discovered from the file extension.
#    type = 
#  }
#}
