name = "ellipsys-datastage-plugin"
code = "ellipsys-datastage-plugin"
connector_id = "ellipsys-datastage"
enabled = true

connection.url = "jdbc:duckdb:/path/to/duckdb/dump"
field-level-lineage.enabled = false
projects = "projet_A,projet_B"
