name = ""
code = ""
connector_id = "matillion-v2"
enabled = true

# Define secret manager for this connection. 
# This configuration only works with Scanner 73+ and needs a functional secret manager configured in the scanner configuration file.
#secret_manager {
#    enabled = true
#    key = "<secret_name>"
#}

connection {
    # The URL of the Matillion server. eg: https://matillion.example.com
    url = ""
    # User name
    username = ""
    # User Password
    password = ""
	
	# custom http client timeout in ms (default 180000 ms)
	# e.g. : timeout = 300000 
	#  - After 5 mn, if no http response received, a timeout exception throw
	# timeout =
}



# Filter used to keep only items that match this filter.
#
# Use universal filter language described in documentation.
# https://docs.actian.com/data-intelligence-platform/technical-documentation/scanners/zeenea-universal-filters.html
#
# Rules filter keys are :
# - group : Matillion group name
# - project : Matillion project name
# - job : Matillion job name
#
# Example:
#filters = [
#  {
#    id="accept_zeenea_project"
#    action = ACCEPT
#    rules {
#      project = "ZEENEA*"
#    }
#  },
#  {
#    id = "default_reject"
#    action = REJECT
#  }
#]
#
# filters = []

# List of version rules separated by a comma.
#
# Only one version of a project is synchronized.
# The rules are used to define which version of a project should be synchronized.
#
# Each rules consist of three segments separated by a slash "/".
# The first segment is a pattern that should match the group name.
# The second segment is a pattern that should match the project name.
# The last one is the version name to use. It can uses variable if caturing groups have been defined in the other regex.
#
# If the project matches no rule, the synchronized version will be "default".
#
# Example: versions="g1/p1/v1,group(\d+)/project(\d+)/version_$1_$2,.*/.*/other_default"
#    1 - g1/p1/v1 : The version "v1" of project "p1" of the group "g1" will be synchronized.
#    2 - g(\d+)/p(\d+)/v_$1_$2 : For all project "p<num>" ("p1", "p2"…) in groups "g<num>" ("g1", "g2"…) the version v_<num_group>_<num_project> will be synchronized.
#    3 - for others groups/projects, the "other_default" version will be used.
#
#versions = """"""

# tls {
#   truststore {
#     # Path to the trust store file
#     path = ""
#     # Password of the trust store file.
#     password = "changeit"
#     # Type of the trust store file. (PKCS12 ou JKS), default value is discovered from the file extension.
#     #type = ""
#   }
#   # By Pass Certificate Validation, default is false. (should be kept false)
#   #bypass_certificate_validation = "true"
# }

# proxy {
#     #  proxy scheme (choose https or http)
#     scheme =
#     hostname =
#     port =
#     #username =
#     #password =
# }
