name = ""
code = ""
connector_id = "snowflake-v2"
enabled = true

# Define secret manager for this connection. 
# This configuration only works with Scanner 73+ and needs a functional secret manager configured in the scanner configuration file.
#secret_manager {
#    enabled = true
#    key = "<secret_name>"
#}

connection {
    # JDBC URL (see: https://docs.snowflake.com/en/developer-guide/jdbc/jdbc-configure)
    #
    # Acount identifier is typically "<orgname>-<account_name>" (see: https://docs.snowflake.com/en/user-guide/admin-account-identifier)
    # The "db" parameter is always required to initialize the connection. 
    # Role and Warehouse parameters are optional if the user hase default values defined.
    #
    url = "jdbc:snowflake://<account_identifier>.snowflakecomputing.com/?db=<database>&role=<role>&warehouse=<warehouse>"
    username = ""
    password = ""
    #private_key_path = ""
    #passphrase = ""
}


# Multi account support.
# multi_account {
    # Manually define which account to connect to. It must be a list of <organisation_name>-<account-name>, separated by a space.
    # list = "orgname-account1 orgname-account2"
#}

# Enable data classificartion metadata retrival from Snowflake if enabled (disabled by default)
#data_classification.enabled = "true"

# Enable user defined tags metadata retrival from Snowflake if enabled (disabled by default)
#user_defined_tags.enabled = "true"

#
# By enabling the cache, you can improve the performance of the update schema operations by switching the update schema 
# from unitary queries to assembly queries. Instead of executing four queries per imported table, the connector only execute four queries per catalog.
# The result is stored in a file in the folder given as a parameter and is reused during the time-to-live period.
# The avoid  again the queries between two small imports operations.
# The size of the file depends on the number of tables in the database.
#
# Warning: Currently, enabling cache automatically disable pipe and history lineage.
# This limitation should be removed in a future release.
#
cache {
    # Enables the cache
    enabled = false

    # Folder were caches are stored, if not set cache will be stored in memory.
    #folder = "/path/to/zeenea-scanner/cache"
    
    # Cache time-to-live period. (Don't apply to memory cache)
    # Format: ISO-8601 (PnDTnHnMn.nS) ; example: "P1D": 1 day, "PT12H": 12 hours 
    # Default: 12 Hours
    #ttl = "PT12H"
}

# Lineage section
#lineage {
#    view.enabled = true
#    pipe.enabled = false
#    history {
#       enabled = false
#
#       # The name of the Warehouse where the queries are executed.
#       #warehouse = ""
#
#       # Number of days to analyse the queries between the start of the extraction and this number.
#       period = "10"
#    }
#}

# Filter used to keep only items that match this filter.
#
# Use universal filter language described in documentation.
# https://docs.actian.com/data-intelligence-platform/technical-documentation/scanners/zeenea-universal-filters.html
#
# Rules filter keys are :
# - account : Snowflake account name
# - catalog : Snowflake catalog name
# - schema : Snowflake schema name
# - table : Snowflake table name
#
# Example:
#filters = [
#  {
#    id="accept_zeenea_catalog"
#    action = ACCEPT
#    rules {
#      catalog = "ZEENEA*"
#    }
#  },
#  {
#    id = "default_reject"
#    action = REJECT
#  }
#]
#
# filters = []

# proxy {
#     #  proxy scheme (choose https or http)
#     scheme =
#     hostname =
#     port =
#     #username =
#     #password =
# }
